spring:
  security:
      user:
        name: admin
        password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.0.14:3306/spring-security
    username: root
    password: 12345678
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456
#server:
#  servlet:
#    contextPath: /api
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs

